import "./globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import SastaCoffeeLogo from "./assets/icons/icon-sasta-coffee.png";
import Image from "next/image";
import Navbar from "./components/UI/Navbar";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        <Navbar />
        {children}
        <div className="flex flex-col px-12 py-8 font-medium md:flex-row md:justify-between">
          <div>
            <img
              src={"icons/icon-sasta-coffee-secondary.png"}
              alt="logo-sasta-coffee"
              className="mb-2 h-24"
            />
            <h5>Experience the satisfaction of enjoying Indonesian coffee.</h5>
            <p className="text-sm font-normal text-gray-400">
              Copyright 2023 © Sasta Coffee
            </p>
          </div>
          <div className="mt-8 md:mt-0">
            <h4 className="mb-2 text-3xl font-semibold">Contact Us</h4>
            <p>(+62) 81809035905</p>
            <p>(+62) 87823895139</p>
            <p>ini_nanti_diganti@rocketmail.com</p>
          </div>
        </div>
      </body>
    </html>
  );
}
